### ISSUE TITLE
[Crash]: Crash after have tweaked "some" of the ExNihilo Recipes using Modtweaker Script

### ISSUE THREAD

**Issue by Lanse505** [bdew-minecraft/neiaddons#22] opened 2015-01-08 20:36 UTC
Hello Bdew!, I got this crashlog after i removed some of the hammer recipes i didnt feel were appropriate to the HQM-based Map i'm making ^^'.

Crashlog:
http://pastebin.com/eM7UgSLx

Script:
http://pastebin.com/Q2c83mg2

**Comment by bdew** [comment] 2015-01-09 05:52
I can't reproduce this, tho i didn't try with all the mods mentioned in your file. 

From the look of your log you end up with null entries in the hammer recipe list, i'll try adding a workaround.

**Comment by bdew** [comment] 2015-01-09 11:03
Try this build http://jenkins.bdew.net/job/neiaddons-1.7.10/13/artifact/build/libs/neiaddons-mc1710-1.12.3.13.jar

**Comment by Lanse505** [comment] 2015-01-09 11:39
Well onto the next mod dev, 1.) NEI dont registers the Modtweaker change properly but it doesnt crash. 2.) this happens when you try breaking a block: http://pastebin.com/6aPYcxvc

**Comment by bdew** [comment] 2015-01-09 11:43
Well whatever put those nulls in there (i'm not entirely sure it's modtweaker fault) is messing up Ex Nihilo in the same way it was messing my mod :P

I'm going to close this as it's supposedly fixed. If you manage to get the changes to work with EN properly and they still don't show up in NEI - comment here or open a new bug report.

**Closed as completed by bdew** 2015-01-09 11:43 UTC

**Comment by Lanse505** [comment] 2015-01-09 11:49
Will do, Idk why it would do this either. The Sieve removal recipes works perfectly however Hammer Recipes is the thing causing issues >.>
